<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Faker\Factory as Faker;
use Carbon\Carbon;

class ressourceseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $resources = [
    [
        'type' => 'Ordinateur',
        'designation' => 'PC portable pro',
        'marque' => 'Dell',
        'modele' => 'XPS13',
        'numero_serie' => 'SN12345678',
        'version_logiciel' => null,
        'date_achat' => '2021-05-10',
        'etat' => 'Neuf',
        'localisation' => 'Bureau Marrakech',
        'utilisateur_affecte' => 'Ali Benjelloun',
        'date_fin_garantie' => '2023-05-10',
        'prochaine_maintenance' => '2025-02-15',
        'duree_vie_mois' => 36,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Acheté pour l’équipe commerciale',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Logiciel',
        'designation' => 'Suite bureautique',
        'marque' => 'Microsoft',
        'modele' => 'Office 365',
        'numero_serie' => 'LIC98765432',
        'version_logiciel' => 'v2102',
        'date_achat' => '2020-08-01',
        'etat' => 'Bon',
        'localisation' => 'Cloud',
        'utilisateur_affecte' => 'Service administratif',
        'date_fin_garantie' => '2023-08-01',
        'prochaine_maintenance' => '2024-07-20',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 50,
        'remarque' => 'Licence annuelle renouvelable',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Imprimante',
        'designation' => 'Imprimante laser A4',
        'marque' => 'HP',
        'modele' => 'LaserJet Pro',
        'numero_serie' => 'SN11223344',
        'version_logiciel' => null,
        'date_achat' => '2019-11-15',
        'etat' => 'Usagé',
        'localisation' => 'Bureau Casablanca',
        'utilisateur_affecte' => 'Service communication',
        'date_fin_garantie' => '2021-11-15',
        'prochaine_maintenance' => '2024-10-01',
        'duree_vie_mois' => 48,
        'est_amortie' => true,
        'quantite' => 2,
        'remarque' => 'Entretien régulier nécessaire',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Serveur',
        'designation' => 'Serveur principal',
        'marque' => 'IBM',
        'modele' => 'X3650',
        'numero_serie' => 'SRV99887766',
        'version_logiciel' => null,
        'date_achat' => '2018-01-10',
        'etat' => 'Bon',
        'localisation' => 'Data center',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2021-01-10',
        'prochaine_maintenance' => '2025-01-10',
        'duree_vie_mois' => 60,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Garanti par contrat de maintenance',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Switch',
        'designation' => 'Switch réseau 24 ports',
        'marque' => 'Cisco',
        'modele' => 'SG300',
        'numero_serie' => 'SW12344321',
        'version_logiciel' => null,
        'date_achat' => '2017-09-05',
        'etat' => 'Usagé',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2019-09-05',
        'prochaine_maintenance' => '2024-05-15',
        'duree_vie_mois' => 48,
        'est_amortie' => true,
        'quantite' => 3,
        'remarque' => 'À remplacer dans 6 mois',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Routeur',
        'designation' => 'Routeur VPN',
        'marque' => 'Juniper',
        'modele' => 'SRX300',
        'numero_serie' => 'RT12345678',
        'version_logiciel' => null,
        'date_achat' => '2020-03-20',
        'etat' => 'Bon',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2023-03-20',
        'prochaine_maintenance' => '2024-12-10',
        'duree_vie_mois' => 60,
        'est_amortie' => false,
        'quantite' => 2,
        'remarque' => 'Mise à jour du firmware planifiée',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Ordinateur',
        'designation' => 'PC bureau fixe',
        'marque' => 'HP',
        'modele' => 'EliteDesk 800',
        'numero_serie' => 'SN87654321',
        'version_logiciel' => null,
        'date_achat' => '2022-07-15',
        'etat' => 'Neuf',
        'localisation' => 'Bureau Rabat',
        'utilisateur_affecte' => 'Sara Bennis',
        'date_fin_garantie' => '2024-07-15',
        'prochaine_maintenance' => '2025-07-01',
        'duree_vie_mois' => 36,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Remplacement prévu dans 3 ans',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Logiciel',
        'designation' => 'Antivirus entreprise',
        'marque' => 'Kaspersky',
        'modele' => 'Endpoint Security',
        'numero_serie' => 'LIC55667788',
        'version_logiciel' => 'v5.4',
        'date_achat' => '2021-02-10',
        'etat' => 'Bon',
        'localisation' => 'Cloud',
        'utilisateur_affecte' => 'Tous utilisateurs',
        'date_fin_garantie' => '2023-02-10',
        'prochaine_maintenance' => '2024-03-01',
        'duree_vie_mois' => 24,
        'est_amortie' => false,
        'quantite' => 100,
        'remarque' => 'Licence annuelle à renouveler',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Imprimante',
        'designation' => 'Imprimante multifonction',
        'marque' => 'Canon',
        'modele' => 'iR ADV',
        'numero_serie' => 'SN44332211',
        'version_logiciel' => null,
        'date_achat' => '2018-06-12',
        'etat' => 'Usagé',
        'localisation' => 'Bureau Tanger',
        'utilisateur_affecte' => 'Service commercial',
        'date_fin_garantie' => '2020-06-12',
        'prochaine_maintenance' => '2024-11-20',
        'duree_vie_mois' => 48,
        'est_amortie' => true,
        'quantite' => 1,
        'remarque' => 'Problèmes récurrents avec le scanner',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Serveur',
        'designation' => 'Serveur backup',
        'marque' => 'Dell',
        'modele' => 'PowerEdge T40',
        'numero_serie' => 'SRV66778899',
        'version_logiciel' => null,
        'date_achat' => '2020-12-01',
        'etat' => 'Neuf',
        'localisation' => 'Data center',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2023-12-01',
        'prochaine_maintenance' => '2025-01-15',
        'duree_vie_mois' => 60,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Disque dur SSD installé',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Switch',
        'designation' => 'Switch réseau 48 ports',
        'marque' => 'Netgear',
        'modele' => 'GS748T',
        'numero_serie' => 'SW99887766',
        'version_logiciel' => null,
        'date_achat' => '2019-03-25',
        'etat' => 'Bon',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2022-03-25',
        'prochaine_maintenance' => '2024-06-01',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 2,
        'remarque' => 'Fonctionne sans problème',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Routeur',
        'designation' => 'Routeur 4G LTE',
        'marque' => 'Huawei',
        'modele' => 'B525',
        'numero_serie' => 'RT55443322',
        'version_logiciel' => null,
        'date_achat' => '2021-04-18',
        'etat' => 'Neuf',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2024-04-18',
        'prochaine_maintenance' => '2025-05-01',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Bonne couverture réseau',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Ordinateur',
        'designation' => 'PC bureau fixe',
        'marque' => 'Lenovo',
        'modele' => 'ThinkCentre M720',
        'numero_serie' => 'SN66554433',
        'version_logiciel' => null,
        'date_achat' => '2020-10-10',
        'etat' => 'Bon',
        'localisation' => 'Bureau Fès',
        'utilisateur_affecte' => 'Khalid Lamrani',
        'date_fin_garantie' => '2023-10-10',
        'prochaine_maintenance' => '2024-11-10',
        'duree_vie_mois' => 36,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Installation récente',
        'created_at' => now(),
        'updated_at' => now(),
    ],
];
 $resources = array_merge($resources, [
    [
        'type' => 'Logiciel',
        'designation' => 'Gestion comptable',
        'marque' => 'Sage',
        'modele' => '100cloud',
        'numero_serie' => 'LIC11223344',
        'version_logiciel' => 'v3.2',
        'date_achat' => '2019-09-01',
        'etat' => 'Bon',
        'localisation' => 'Cloud',
        'utilisateur_affecte' => 'Service comptabilité',
        'date_fin_garantie' => '2022-09-01',
        'prochaine_maintenance' => '2024-03-01',
        'duree_vie_mois' => 36,
        'est_amortie' => true,
        'quantite' => 20,
        'remarque' => 'Licence sous abonnement',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Imprimante',
        'designation' => 'Imprimante jet d’encre',
        'marque' => 'Epson',
        'modele' => 'Stylus Photo',
        'numero_serie' => 'SN33445566',
        'version_logiciel' => null,
        'date_achat' => '2017-08-20',
        'etat' => 'Hors Service',
        'localisation' => 'Bureau Tanger',
        'utilisateur_affecte' => 'Service marketing',
        'date_fin_garantie' => '2019-08-20',
        'prochaine_maintenance' => '2024-09-01',
        'duree_vie_mois' => 36,
        'est_amortie' => true,
        'quantite' => 1,
        'remarque' => 'Réparations non rentables',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Serveur',
        'designation' => 'Serveur d’applications',
        'marque' => 'HP',
        'modele' => 'ProLiant DL380',
        'numero_serie' => 'SRV55667788',
        'version_logiciel' => null,
        'date_achat' => '2018-11-11',
        'etat' => 'Bon',
        'localisation' => 'Data center',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2021-11-11',
        'prochaine_maintenance' => '2024-12-15',
        'duree_vie_mois' => 60,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Montée en charge prévue',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Switch',
        'designation' => 'Switch réseau 16 ports',
        'marque' => 'TP-Link',
        'modele' => 'TL-SG1016',
        'numero_serie' => 'SW55667788',
        'version_logiciel' => null,
        'date_achat' => '2020-05-05',
        'etat' => 'Neuf',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2023-05-05',
        'prochaine_maintenance' => '2025-04-10',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Installation récente',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Routeur',
        'designation' => 'Routeur Wi-Fi',
        'marque' => 'TP-Link',
        'modele' => 'Archer C7',
        'numero_serie' => 'RT77889900',
        'version_logiciel' => null,
        'date_achat' => '2019-06-15',
        'etat' => 'Bon',
        'localisation' => 'Bureau Marrakech',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2022-06-15',
        'prochaine_maintenance' => '2024-07-10',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Fonctionne sans problème',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Ordinateur',
        'designation' => 'Ultrabook',
        'marque' => 'Apple',
        'modele' => 'MacBook Air',
        'numero_serie' => 'SN99887766',
        'version_logiciel' => null,
        'date_achat' => '2021-12-20',
        'etat' => 'Neuf',
        'localisation' => 'Bureau Casablanca',
        'utilisateur_affecte' => 'Imane El Fassi',
        'date_fin_garantie' => '2023-12-20',
        'prochaine_maintenance' => '2025-01-10',
        'duree_vie_mois' => 36,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Excellent pour mobilité',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Logiciel',
        'designation' => 'Logiciel de CRM',
        'marque' => 'Salesforce',
        'modele' => 'Lightning',
        'numero_serie' => 'LIC44556677',
        'version_logiciel' => 'v5.1',
        'date_achat' => '2019-07-22',
        'etat' => 'Bon',
        'localisation' => 'Cloud',
        'utilisateur_affecte' => 'Service commercial',
        'date_fin_garantie' => '2022-07-22',
        'prochaine_maintenance' => '2024-05-15',
        'duree_vie_mois' => 36,
        'est_amortie' => true,
        'quantite' => 30,
        'remarque' => 'Licence avec support',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Imprimante',
        'designation' => 'Imprimante 3D',
        'marque' => 'Ultimaker',
        'modele' => 'S5',
        'numero_serie' => 'SN55664433',
        'version_logiciel' => null,
        'date_achat' => '2020-09-30',
        'etat' => 'Bon',
        'localisation' => 'Laboratoire',
        'utilisateur_affecte' => 'Equipe R&D',
        'date_fin_garantie' => '2023-09-30',
        'prochaine_maintenance' => '2024-12-01',
        'duree_vie_mois' => 36,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Utilisée pour prototypage',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Serveur',
        'designation' => 'Serveur de messagerie',
        'marque' => 'IBM',
        'modele' => 'System x3650 M5',
        'numero_serie' => 'SRV33445566',
        'version_logiciel' => null,
        'date_achat' => '2018-05-14',
        'etat' => 'Usagé',
        'localisation' => 'Data center',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2021-05-14',
        'prochaine_maintenance' => '2024-08-20',
        'duree_vie_mois' => 60,
        'est_amortie' => true,
        'quantite' => 1,
        'remarque' => 'À planifier un remplacement',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'type' => 'Switch',
        'designation' => 'Switch PoE 24 ports',
        'marque' => 'Cisco',
        'modele' => 'Catalyst 2960X',
        'numero_serie' => 'SW77889900',
        'version_logiciel' => null,
        'date_achat' => '2021-01-25',
        'etat' => 'Neuf',
        'localisation' => 'Salle serveurs',
        'utilisateur_affecte' => 'Equipe IT',
        'date_fin_garantie' => '2024-01-25',
        'prochaine_maintenance' => '2025-02-01',
        'duree_vie_mois' => 48,
        'est_amortie' => false,
        'quantite' => 1,
        'remarque' => 'Installation récente',
        'created_at' => now(),
        'updated_at' => now(),
    ],
]);
foreach ($resources as $resource) {
        DB::table('resource')->insert($resource);
    }

    }
}
